services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./docker/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: huhu-todos
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  # Laravel Dusk用のselenium
  selenium:
      image: selenium/standalone-chrome:latest
      container_name: selenium
      platform: linux/amd64
      environment:
          - ACCEPT_INSECURE_CERTS=true
      shm_size: '2g'
      volumes:
          - /dev/shm:/dev/shm
      ports:
          - "4444:4444"
          - "7900:7900"
      networks:
          - app-network
      extra_hosts:
          - "host.docker.internal:host-gateway"

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
