name: Tests

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: dokcer compose Laravel Init
        run: |
          docker compose up -d
          docker compose exec app composer install
          docker compose exec app cp .env.example .env
          docker compose exec app php artisan key:generate
          docker compose exec app php artisan config:cache

      - name: Prepare Test Database
        run: |
          sleep 10
          docker compose exec db mysql -uroot -proot -e "CREATE DATABASE IF NOT EXISTS test_todos;"
          docker compose exec db mysql -uroot -proot -e "SHOW TABLES FROM test_todos";

      - name: Show Pre-test Log
        run: docker compose exec app cat storage/logs/laravel.log || true

      - name: Exec Phpunit
        run: |
          docker compose exec -e XDEBUG_MODE=off app php artisan test --env=testing || true

      # テスト実行後にログを確認（テストが失敗しても実行される）
      - name: Show Post-test Log
        if: always()
        run: docker compose exec app cat storage/logs/laravel.log
